### ISSUE TITLE
Any particular reason why this package only supports Dart >=1.9.0-edge?

### ISSUE THREAD

**Issue by crunchex** [DirectMyFile/console.dart#5]
It's a bit tough to get the latest builds of Dart from source - not that it's impossible, just a hassle the way they have it set up. Is there any particular reason why this package wouldn't be compatible with 1.8.5 (current stable)?

**Comment by Term1nal** [comment]
The original developer wishes for this only to operate with latest version, as for his reasoning I was unable to contact him at the time of this posting to inquire. I think due to async/await calls if I remember the justification correctly from conversations on IRC, but I am not entirely sure. There are nightly binaries to 1.9 you can download (and avoid compiling from source). https://www.dartlang.org/tools/download-archive/

As well, you can manually modify the version required but surely that will of course come with the caveat that it's not supported/recommended to go against the dep and have unforeseen consequences.

**Comment by crunchex** [comment]
Thanks for the quick reply and link to the download-archive - I wasn't even aware of it.

**Comment by kaendfinger** [comment]
Yes :) Async/Await and also the synchronous IO related to `stdout`
